# Generated by Django 4.2.7 on 2024-01-26 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorisation', '0002_statistic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Statistic',
        ),
    ]
