# Generated by Django 4.2.7 on 2024-02-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorisation', '0003_delete_statistic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default=None, upload_to='authorisation/images/profile_avatar', verbose_name='Images'),
        ),
    ]
