# Generated by Django 4.2.7 on 2023-11-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Available'),
        ),
    ]
