# Generated by Django 4.2.7 on 2023-11-16 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_websites'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAttended',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('proxy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.proxy', verbose_name='Proxy')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.websites', verbose_name='Site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Site attended',
                'verbose_name_plural': 'Sites attended',
            },
        ),
    ]
